name: check
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Stackage check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            ~/.stackage/curator/cache
          key: ${{ runner.os }}-stackage-nightly-${{ hashFiles('**/build-constraints.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - run: etc/check.sh
